/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";



export function Airplane(props) {
  const { nodes, materials } = useGLTF("./models/airplane/CloudShip.glb");


  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 59.417, 0]} rotation={[-Math.PI / 2, -1.57, 0]}>
            <mesh geometry={nodes.balloon_flying_ship_balloon_flying_ship_0.geometry} material={nodes.balloon_flying_ship_balloon_flying_ship_0.material} position={[0.148, -0.283, -28.919]} />
          </group>
          <group position={[-9.264, -8.344, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.661}>
            <mesh geometry={nodes.flying_ship_flying_ship_0.geometry} material={nodes.flying_ship_flying_ship_0.material} position={[4.55, 0, 8.344]} />
          </group>
          <group position={[4.152, -1.003, 0.005]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.cabin_flying_ship_cabin_flying_ship_0.geometry} material={nodes.cabin_flying_ship_cabin_flying_ship_0.material} position={[0, 0.005, 1]} />
          </group>
          <group position={[4.152, -1.003, 0.005]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.window_flying_ship_window_door_flying_ship_0.geometry} material={nodes.window_flying_ship_window_door_flying_ship_0.material} position={[0, 0.005, 1]} />
          </group>
          <group position={[4.152, -1.003, 0.005]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.door_part_flying_ship_window_door_flying_ship_0.geometry} material={nodes.door_part_flying_ship_window_door_flying_ship_0.material} position={[0, 0.005, 1]} />
          </group>
          <group position={[17.24, 0.545, -2.16]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-13.088, -2.165, -1.549]}>
              <mesh geometry={nodes.door_door_part_3_flying_ship_0.geometry} material={nodes.door_door_part_3_flying_ship_0.material} />
              <mesh geometry={nodes.door_door_part_4_flying_ship_0.geometry} material={nodes.door_door_part_4_flying_ship_0.material} />
              <mesh geometry={nodes.door_flying_ship_0.geometry} material={nodes.door_flying_ship_0.material} />
            </group>
          </group>
          <group position={[34.774, 2.247, 0]}>
            <group position={[-3.374, 1.185, 0]}>
              <mesh geometry={nodes.Line017_door_part_3_flying_ship_0.geometry} material={nodes.Line017_door_part_3_flying_ship_0.material} />
              <mesh geometry={nodes.Line017_paddle_flying_ship_0.geometry} material={nodes.Line017_paddle_flying_ship_0.material} />
            </group>
          </group>
          <group position={[34.774, 2.247, 0]} rotation={[1.358, 1.55, 0.221]} scale={[0.614, 0.634, 0.845]}>
            <group position={[-0.621, -42.192, -4.887]}>
              <mesh geometry={nodes.paddle_flying_ship010_paddle_flying_ship_0.geometry} material={nodes.paddle_flying_ship010_paddle_flying_ship_0.material} />
              <mesh geometry={nodes.paddle_flying_ship010_sail_flying_ship_0.geometry} material={nodes.paddle_flying_ship010_sail_flying_ship_0.material} />
            </group>
          </group>
          <group position={[34.774, 2.247, 0]} rotation={[0.572, 1.55, 0.221]} scale={[0.614, 0.634, 0.845]}>
            <group position={[-0.621, -42.192, -4.887]}>
              <mesh geometry={nodes.paddle_flying_ship011_paddle_flying_ship_0.geometry} material={nodes.paddle_flying_ship011_paddle_flying_ship_0.material} />
              <mesh geometry={nodes.paddle_flying_ship011_sail_flying_ship_0.geometry} material={nodes.paddle_flying_ship011_sail_flying_ship_0.material} />
            </group>
          </group>
          <group position={[34.774, 2.247, 0]} rotation={[-0.213, 1.55, 0.221]} scale={[0.614, 0.634, 0.845]}>
            <group position={[-0.621, -42.192, -4.887]}>
              <mesh geometry={nodes.paddle_flying_ship012_paddle_flying_ship_0.geometry} material={nodes.paddle_flying_ship012_paddle_flying_ship_0.material} />
              <mesh geometry={nodes.paddle_flying_ship012_sail_flying_ship_0.geometry} material={nodes.paddle_flying_ship012_sail_flying_ship_0.material} />
            </group>
          </group>
          <group position={[34.774, 2.247, 0]} rotation={[-0.998, 1.55, 0.221]} scale={[0.614, 0.634, 0.845]}>
            <group position={[-0.621, -42.192, -4.887]}>
              <mesh geometry={nodes.paddle_flying_ship013_paddle_flying_ship_0.geometry} material={nodes.paddle_flying_ship013_paddle_flying_ship_0.material} />
              <mesh geometry={nodes.paddle_flying_ship013_sail_flying_ship_0.geometry} material={nodes.paddle_flying_ship013_sail_flying_ship_0.material} />
            </group>
          </group>
          <group position={[34.774, 2.247, 0]} rotation={[-1.784, 1.55, 0.221]} scale={[0.614, 0.634, 0.845]}>
            <group position={[-0.621, -42.192, -4.887]}>
              <mesh geometry={nodes.paddle_flying_ship014_paddle_flying_ship_0.geometry} material={nodes.paddle_flying_ship014_paddle_flying_ship_0.material} />
              <mesh geometry={nodes.paddle_flying_ship014_sail_flying_ship_0.geometry} material={nodes.paddle_flying_ship014_sail_flying_ship_0.material} />
            </group>
          </group>
          <group position={[34.774, 2.247, 0]} rotation={[-2.569, 1.55, 0.221]} scale={[0.614, 0.634, 0.845]}>
            <group position={[-0.621, -42.192, -4.887]}>
              <mesh geometry={nodes.paddle_flying_ship015_paddle_flying_ship_0.geometry} material={nodes.paddle_flying_ship015_paddle_flying_ship_0.material} />
              <mesh geometry={nodes.paddle_flying_ship015_sail_flying_ship_0.geometry} material={nodes.paddle_flying_ship015_sail_flying_ship_0.material} />
            </group>
          </group>
          <group position={[34.774, 2.247, 0]} rotation={[2.929, 1.55, 0.221]} scale={[0.614, 0.634, 0.845]}>
            <group position={[-0.621, -42.192, -4.887]}>
              <mesh geometry={nodes.paddle_flying_ship016_paddle_flying_ship_0.geometry} material={nodes.paddle_flying_ship016_paddle_flying_ship_0.material} />
              <mesh geometry={nodes.paddle_flying_ship016_sail_flying_ship_0.geometry} material={nodes.paddle_flying_ship016_sail_flying_ship_0.material} />
            </group>
          </group>
          <group position={[34.774, 2.247, 0]} rotation={[2.143, 1.55, 0.221]} scale={[0.614, 0.634, 0.845]}>
            <group position={[-0.621, -42.192, -4.887]}>
              <mesh geometry={nodes.paddle_flying_ship017_paddle_flying_ship_0.geometry} material={nodes.paddle_flying_ship017_paddle_flying_ship_0.material} />
              <mesh geometry={nodes.paddle_flying_ship017_sail_flying_ship_0.geometry} material={nodes.paddle_flying_ship017_sail_flying_ship_0.material} />
            </group>
          </group>
          <group position={[-9.524, 0.545, -2.16]} rotation={[-Math.PI / 2, 0, -Math.PI / 3]}>
            <group position={[13.676, -2.165, -1.549]}>
              <mesh geometry={nodes.door004_door_part_3_flying_ship_0.geometry} material={nodes.door004_door_part_3_flying_ship_0.material} />
              <mesh geometry={nodes.door004_door_part_4_flying_ship_0.geometry} material={nodes.door004_door_part_4_flying_ship_0.material} />
              <mesh geometry={nodes.door004_flying_ship_0.geometry} material={nodes.door004_flying_ship_0.material} />
            </group>
          </group>
          <mesh geometry={nodes.rope_flying_ship_rope_flying_ship_0.geometry} material={nodes.rope_flying_ship_rope_flying_ship_0.material} position={[28.919, 59.565, 0.283]} rotation={[Math.PI / 2, -1.57, 0]} scale={[-1, 1, 1]} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/airplane/CloudShip.glb");
